### PR TITLE
Added OCP Build Pipeline

### PR DESCRIPTION
**Pull request by maxveit**
- Switched the Dockerfile to multi-stage to combine build and run in a single file
- Added the pipeline-template to create the build pipeline in OCP
- Added the manifests/deploy-openshift.yaml which changes the Deployment to a DeploymentConfig that reacts on ImageStream Change Triggers for re-deployment

### CODE REVIEW

**Comment by jwalcorn** [comment]
Did you delete the Apache license comments from the Dockerfile?  Also, I don't think we need those `RUN ls` lines anymore - don't want to end up with extra layers in the Docker image because of that.

**Comment by jwalcorn** [comment]
Also, it looks like the change history shows edits to the deploy.yaml, then a rename - so there's a merge conflict due to that deploy.yaml.  can you make it so you haven't touched deploy.yaml, but rather simply created a brand new file with the DeploymentConfig?

**Comment by jwalcorn** [comment]
Sorry to keep piling on, but we probably don't want to hard-code the namespace for the ImageStream to be `jenkins` either, as that is a misleading name since Jenkins isn't actually being used here.  What's the downside to just using the currently configured namespace (often `stock-trader` - whatever `oc login` gives you, or you explicitly switch to via `oc project`), with appropriately named objects?

Oh, and I see that change you made to add "demo :)" to that doc file during your live demo to me is in there....  ;)

**Comment by rtclauss** [comment]
One comment, if you're using GHE or a private repo that is secured and requires ssh keys to authenticate, make sure you use the `git@github.com:....` pattern when entering the `GIT_SOURCE_URL`

**Comment by jwalcorn** [comment]
Used new PR (#7) to do this, so closing this one out.

**Pull request closed without merging**
