### PR TITLE
Use WebSphere Liberty helm chart to deploy trader microservice

### PR DESCRIPTION
**Pull request by leochr**
- Use WebSphere Liberty helm chart to deploy trader microservice
- Enabled Monitoring

### CODE REVIEW

**Comment by leochr** [comment]
@jwalcorn The `nodePort` field is hardcoded in the `Service` under `deploy.yaml`. Wondering if that's really necessary. In the event of port collisions, the system would be unable to allocate that port.

https://github.com/IBMStockTrader/trader/blob/4e2c701e6706cfb3e931a1ba6b2dffc5c748daa3/manifests/deploy.yaml#L100

**Comment by jwalcorn** [comment]
We had been hardcoding that because we needed to register the redirect URL for IBMid, and we needed to be able to predict that URL ahead of time.  But lately we've not been using the OpenID Connect path (to IBMid), but have instead been using just basicRegistry.  Also, we have adopted Ingress now, so we are trying to wean ourselves off of node ports.

**Comment by jwalcorn** [comment]
I've also been having some health endpoint discussions with @kyleschlosser.  Can this be used to specify a readinessProbe?

**Comment by leochr** [comment]
@jwalcorn thanks for the response. Glad that we don't need to include/worry-about `nodePort`.

Right now, our chart uses `/` (or `/health` if MicroProfile Health is enabled) to determine readiness. We are enhancing our Liberty to chart to allow custom readinessProbe, so users can specify a custom endpoint instead (e.g. `/trader`).

**Comment by jwalcorn** [comment]
So where do I define my Ingress?  Right now, there are 3 Kubernetes objects defined in my full deploy.yaml: the deployment, the service, and the ingress.  I think the Liberty helm chart is doing the service for me.  But what about the ingress?

**Comment by jwalcorn** [comment]
Oh, never mind.  I see the `ingress:` section in the trader-values.yaml now.

**Pull request merged**
